### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by craigryan** [hfaran/slack-export-viewer#29]
I made one slight change to this most excellent tool to get it running with python 3.5. I'm no python dev so I'm simply applying a fix suggested on a forum:

In app.py change both occurrences of this line to wrap keys() as a list:

    channels = list(flask._app_ctx_stack.channels.keys())

which solves a failure on startup:

TypeError: 'dict_keys' object does not support indexing

after that it worked perfectly. 

In the startup script slack-export-viewer the first line is then

#!/usr/local/opt/python3/bin/python3.5

Unrelated to this issue, while I'm here, time permitting I'd like to look at extending with full cross channel search.  Interested to hear from anyone else interested in this.

**Comment by hfaran** [comment]
Thanks; fixed this in master. I'll put out a release later.

**Comment by hfaran** [comment]
> Unrelated to this issue, while I'm here, time permitting I'd like to look at extending with full cross channel search. Interested to hear from anyone else interested in this.

This would be a nice feature to eventually add. You should open a new issue for this. :)

**Comment by hfaran** [comment]
> In the startup script slack-export-viewer the first line is then
> 
> #!/usr/local/opt/python3/bin/python3.5

If you want to use python3.5 by default for this, what you should instead of changing the startup script is to change the environment in which you're running this to be python3.5 by default.

But as you said, you're not a python dev, so doing this isn't obvious. In which case, I'd recommend just doing whatever is easiest for you to achieve what you need. :)
