### ISSUE TITLE
Best method to run in production

### ISSUE THREAD

**Issue by feesh** [hfaran/slack-export-viewer#32]
Hi there! :)

Thanks again for building this! I have a few additional questions about running it in production; in particular, I'm using WebFaction as my host, and have set up a `mod_wsgi 4.5.7/Python 2.7` app.

I'm attempting to run it with: `slack-export-viewer -z CMWW\ export\ Nov\ 29\ 2016.zip -p 5000 --no-browser` but presently I only see this output when I load the URL in the browser:

```
Welcome to your mod_wsgi website! It uses:

Python 2.7.12 (default, Sep  2 2016, 21:43:20) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]
WSGI version: (4, 5, 7)
```

Any thoughts?

**Comment by hfaran** [comment]
What steps exactly did you use for setting this up? From what you've mentioned so far, it seems like you're serving content from slack-export-viewer on `localhost:5000` on the server and somehow expecting that to hook up automatically to the Apache/mod_wsgi setup you have going. That's not quite going to work. 😛 

If you want to use mod_wsgi specifically, you'll need to look into the instructions given here in the Flask docs: http://flask.pocoo.org/docs/0.11/deploying/mod_wsgi/

This will require writing just a few lines of code and knowing where to grab the configured app from. Essentially, you would would have to a different version of [`main`](https://github.com/hfaran/slack-export-viewer/blob/master/slackviewer/main.py#L56) that just did configure_app and returned the Flask app object so that you could use it in the .wsgi file as is described in the Flask documentation linked above.

(This is all from my shallow understanding of how mod_wsgi works because I've never personally used it.)

**Comment by hfaran** [comment]
**On the other hand**...

If you want a simple no-frills solution, just run slack-export-viewer with the flags instead: `slack-export-viewer -z <archive_path> --no-browser --ip 0.0.0.0 --port 80` to serve using the built-in werkzeug server directly, without having Apache server in front. Of course, this isn't *recommended* for *production* but that really depends on what you're use case is (if it's serving to only a handful of people and you don't care about exposing your Slack archive to the internet at large, this is fine).

**Comment by hfaran** [comment]
Another solution: [Just use this to just get the HTML itself, and serve that using Apache or nginx directly.](https://github.com/hfaran/slack2html).

**Comment by feesh** [comment]
Ahhh okay, thank you I'll give these steps a try!! Yeah I was definitely expecting the `localhost` launch to "just work" but I see the error of my ways... 😬  Appreciate your help, will let you know how it works out!
