### ISSUE TITLE
Printable export

### ISSUE THREAD

**Issue by benwarfield-usds** [hfaran/slack-export-viewer#77]
This is more of an offer than a request: I recently used slack-export-viewer to produce a printable single-file extract of an entire workspace, for archival purposes. This involved some feature additions and bug fixes, which I've either submitted or am preparing to submit, but also some additional work to produce a command-line script that generates a (mammoth) HTML file that I can then turn into PDF and be confident nobody will come back to me in a month or six asking "how do I open this file?"

If that would be an acceptable contribution, I'll clean it up and make a pull request: since it's a little outside the original scope of the project, though, I'd totally understand not wanting it to get into the main codebase.

**Comment by hfaran** [comment]
Sure thing! Actually, this would be great to work in as a command into [`cli.py`](https://github.com/hfaran/slack-export-viewer/blob/master/slackviewer/cli.py). The commands on there can be used with [`slack-export-viewer-cli`](https://github.com/hfaran/slack-export-viewer/blob/master/setup.py#L37) when it's installed.

You raise a good point about scope, but I think I'm only worried about scope as it pertains to the web app portion of the project (i.e., what happens when you launch app.py); I'm totally okay with whatever useful commands, even if somewhat out-of-scope, anyone can think of to go into cli.py (as long as the command and options are logically laid out, and the logic to do the work fits neatly in the rest of the project).
